### ISSUE TITLE
indexedDB의 데이터를 가져와 sns preview 형태로 렌더링한다.

### ISSUE THREAD

**Issue by heyjoo** [Jooeun-K/octo-generator#4]
## TODO
- [] indexedDB의 데이터를 추상화된 hook을 통해 읽어올 수 있다.
- [] sns preview 화면 UI를 작성한다.
- [] sns preview 화면 UI와 읽어온 데이터를 연결한다.
